📚 Estrutura Essencial de um README
Título: Nome do projeto e uma breve descrição (o que é e para que serve).
Badges (Opcional): Ícones para status de build, licença ou tecnologias.
Como Instalar/Rodar: Passo a passo com comandos para instalar e executar o projeto localmente.
Como Usar: Exemplos claros de uso, com prints ou trechos de código (GIFs são ótimos).
Tecnologias/Stack: Lista de tecnologias utilizadas.
Como Contribuir: Orientações para outros desenvolvedores (para projetos open source).
Licença: Defina o uso do projeto (ex: MIT).
YouTube
YouTube
 +4
💻 Como Criar e Editar (Markdown)
Crie o arquivo: No repositório, crie um arquivo chamado README.md na raiz.
Use Markdown:
# Título (Maior)
## Subtítulo
**Negrito**
[Link](url)
```codigo``` (Bloco de código).
Adicione Imagens: ![Texto](URL_ou_caminho_da_imagem)

# Relatório Operacional de Pré-Decolagem (Atividade Integradora)
Um programa para interpretar dados de telemetria em uma planilha e decidir se a nave está pronta para decolar ou se a decolagem deve ser abortada.

## Como Instalar/Rodar
- Baixar o arquivo .ipynb (Interactive Python Notebook)
- Ter python instalado localmente ou importar no google collab
- Rodar o arquivo

## Como Usar
- Opcional: Pedir para uma AI gerar uma planilha com os dados de telemetria com o prompt abaixo, substituindo os valores entre chaves:
```
Aja como um engenheiro de dados especializado em sistemas aeroespaciais, com foco em simulação de telemetria da nave Starship.

Seu objetivo é gerar um dataset sintético em formato CSV que represente dados de telemetria realistas da Starship durante duas fases críticas: pré-decolagem e ignição dos motores.

Contexto:
A Starship utiliza propelentes criogênicos (metano e oxigênio líquido), motores Raptor e opera sob condições extremas de temperatura e pressão. O dataset será utilizado para simulações e testes de sistemas, portanto deve refletir comportamentos físicos plausíveis com base nessas características.

Instruções:
- Gere um dataset com no mínimo 201 linhas.
- Simule progressão temporal com timestamps sequenciais.
- Inclua duas fases:
  1. Pré-decolagem (sistemas estáveis, preparação)
  2. Ignição (mudanças bruscas em temperatura, pressão e consumo)
- Os dados devem evoluir de forma lógica e consistente.
- Evite valores aleatórios sem coerência física.

Colunas obrigatórias do CSV (usar exatamente estes nomes):
- Timestamp
- Temperatura interna e externa
- Integridade estrutural
- Níveis de energia
- Pressão dos tanques
- Status dos módulos críticos

Regras para os dados:

- temp_interna:
  - Tipo float
  - Deve variar entre {MIN_TEMP_INTERNA}°C e {MAX_TEMP_INTERNA}°C

- temp_externa:
  - Tipo float
  - Pré-decolagem: entre {MIN_TEMP_EXTERNA}°C e {MAX_TEMP_EXTERNA}°C

- integridade_estrutural:
  - Tipo booleano ({OK_INTEGRIDADE_ESTRUTURAL} para intacto e {FALHA_INTEGRIDADE_ESTRUTURAL} para falha)

- nivel_bateria:
  - Tipo float (percentual)
  - Próximo de 100% na pré-decolagem
  - Deve pelo menos {MIN_NIVEL_ENERGIA}% na ignição

- pressao_tanques:
  - Tipo float
  - Pré-decolagem: entre {MIN_PRESSAO_TANQUES} e {MAX_PRESSAO_TANQUES} bar
  - Ignição: aumento para aproximadamente 6.2 bar para alimentar os motores Raptor

- modulos_criticos:
  - Tipo booleano ({OK_MODULOS_CRITICOS} para OK e {FALHA_MODULOS_CRITICOS} para falha)

Regras adicionais:
- Deve haver uma transição clara entre pré-decolagem e ignição
- Os valores devem refletir o comportamento realista da Starship
- Use números decimais quando apropriado
- Mantenha consistência entre variáveis (ex: aumento de pressão antes da ignição, queda leve de bateria, aumento de consumo)

Formato da saída:
- Retorne apenas o CSV
- Inclua cabeçalho na primeira linha
- Use vírgula como separador
- Não inclua explicações, comentários ou qualquer texto fora do CSV
```
- Executar o arquivo .ipynb (Interactive Python Notebook)

- Importar uma planilha com os dados de telemetria com as colunas: timestamp,temperatura_interna,temperatura_externa,integridade_estrutural,nivel_energia,pressao_tanques,modulos_criticos

#Explicação do código

##Bloco 1
Estabelece os limites de segurança para cada variável crítica da nave.

Contém:
- Temperatura interna e externa (mínimo e máximo aceitável).
- Integridade estrutural (OK ou Falha).
- Nível mínimo de energia da bateria.
- Pressão segura dos tanques.
- Status dos módulos críticos.

Esses valores funcionam como “faixas seguras” que serão usados para validar os dados recebidos antes da decolagem.

##Bloco 2a
A parte do código que permite ao usuário insirir valores manualmente para testar se estão dentro das faixas seguras.

- O programa pede cada valor em sequência (temperatura interna, externa, integridade, energia, pressão, módulos).
- Há verificações para garantir que os dados digitados sejam válidos (ex.: números dentro do intervalo, apenas 0 ou 1 para integridade).
- Caso o usuário digite algo errado, o programa mostra uma mensagem de erro e pede para o usuário tentar novamente.

##Bloco 2b
Automatiza a entrada de dados usando um arquivo CSV com cenários de teste.

Contém:
- Um prompt que gera a tabela de telemetria com diferentes cenários (sucesso total e falhas).
- Leitura da planilha com pandas para alimentar o algoritmo de validação.

Permite testar o sistema com muitos cenários diferentes sem precisar digitar manualmente, simulando condições reais de voo e falhas.

##Bloco 3a
Garante que cada valor inserido pelo usuário esteja dentro das faixas seguras definidas no Bloco 1.


- O programa compara cada variável (temperatura interna, externa, integridade, energia, pressão, módulos) com os limites estabelecidos.
- Se algum valor estiver fora da faixa, o sistema aborta a decolagem e informa o motivo específico.
- Se todos os valores estiverem corretos, o sistema libera a decolagem.

Essa lógica simula a checagem final antes do lançamento, evitando que a nave decole em condições inseguras.

##Bloco 3b
Valida automaticamente um conjunto de cenários de telemetria armazenados em arquivo CSV.

- O programa percorre cada linha da planilha.
- Para cada cenário, aplica as mesmas verificações de segurança usadas na entrada manual.
- resultado_final: Indica se a decolagem foi abortada ou autorizada.
- motivo: Explica qual condição falhou (se houver).

##Bloco 4a
Mostra ao usuário uma mensagem com o resultado final com base nos dados inseridos manualmente.

##Bloco 4b
Mostra ao usuário uma mensagem com o resultado final com base nos dados do arquivo CSV.

##Tecnologias
![Python](https://img.shields.io/badge/python-3670A0?style=for-the-badge&logo=python&logoColor=ffdd54)
![Jupyter Notebook](https://img.shields.io/badge/jupyter-%23FA0F00.svg?style=for-the-badge&logo=jupyter&logoColor=white)
![Google Colab](https://img.shields.io/badge/Google%20Colab-%23F9A825.svg?style=for-the-badge&logo=googlecolab&logoColor=white)


# 1. Definir as "Faixas Seguras" (Parâmetros de Voo)

In [ ]:
MIN_TEMP_INTERNA = 18
MAX_TEMP_INTERNA = 27

MIN_TEMP_EXTERNA = -20
MAX_TEMP_EXTERNA = 40

OK_INTEGRIDADE_ESTRUTURAL = 1
FALHA_INTEGRIDADE_ESTRUTURAL = 0

MIN_NIVEL_ENERGIA = 80

MIN_PRESSAO_TANQUES = 50
MAX_PRESSAO_TANQUES = 120

OK_MODULOS_CRITICOS = 1
FALHA_MODULOS_CRITICOS = 0

# 2. Simular a Leitura dos Dados (Telemetria)

##a) Leitura de um conjunto de dados inseridos manualmente

In [ ]:
import sys

dados = 0

while True:
    try:
        match dados:
          case 0:
            temperatura_interna = float(input(f"Digite a temperatura interna em Celsius (>= {MIN_TEMP_INTERNA} e <= {MAX_TEMP_INTERNA}): " ))
          case 1:
            temperatura_externa = float(input(f"\nDigite a temperatura externa em Celsius (>= {MIN_TEMP_EXTERNA} e <= {MAX_TEMP_EXTERNA}): " ))
          case 2:
            integridade_estrutural = int(input(f"\nIntegridade estrutural ({OK_INTEGRIDADE_ESTRUTURAL} = OK e {FALHA_INTEGRIDADE_ESTRUTURAL} = Falha): " ))
            if (integridade_estrutural != OK_INTEGRIDADE_ESTRUTURAL) and (integridade_estrutural != FALHA_INTEGRIDADE_ESTRUTURAL):
              print(f"\nErro! Por favor, digitar apenas {OK_INTEGRIDADE_ESTRUTURAL} ou {FALHA_INTEGRIDADE_ESTRUTURAL}!")
              raise RuntimeError()
          case 3:
            nivel_energia = input(f"\nNível de energia (>= {MIN_NIVEL_ENERGIA}%): " )
            if ("%" in nivel_energia):
              nivel_energia = nivel_energia.replace("%", "")
            nivel_energia = float(nivel_energia)
            if nivel_energia<0 or nivel_energia>100:
              print("\nErro! Por favor, digitar apenas números entre 0 ou 100!")
              raise RuntimeError()
          case 4:
            pressao_tanques = float(input(f"\nPressão dos tanques em bar (>={MIN_PRESSAO_TANQUES} e <={MAX_PRESSAO_TANQUES}): " ))
          case 5:
            modulos_criticos = int(input(f"\nStatus dos módulos críticos ({OK_MODULOS_CRITICOS} = OK e {FALHA_MODULOS_CRITICOS} = Falha): " ))
            if (modulos_criticos != OK_MODULOS_CRITICOS) and (modulos_criticos != FALHA_MODULOS_CRITICOS):
              print(f"\nErro! Por favor, digitar apenas {OK_MODULOS_CRITICOS} ou {FALHA_MODULOS_CRITICOS}!")
              raise RuntimeError()
          case _:
            print("\nDados recebidos com sucesso!")
            break

    except ValueError:
        print("\nErro! Por favor, digitar apenas números, sem letras ou caracteres especiais!")
        print("Vamos tentar de novo...\n")
    except RuntimeError:
        print("Vamos tentar de novo...\n")
    else:
        dados += 1

Digite a temperatura interna em Celsius (>= 18 e <= 27): 20

Digite a temperatura externa em Celsius (>= -20 e <= 40): 20

Integridade estrutural (1 = OK e 0 = Falha): 1

Nível de energia (>= 80%): 90

Pressão dos tanques em bar (>=50 e <=120): 100

Status dos módulos críticos (1 = OK e 0 = Falha): 1

Dados recebidos com sucesso!

## b) Leitura de uma conjunto de dados em uma planilha

###I. Preparar o conjunto de dados

In [ ]:
prompt = f'''
Atue como um Engenheiro de Sistemas Aeroespaciais da Missão Aurora Siger. Preciso de uma tabela de telemetria de pré-decolagem para alimentar um script Python de validação.

Gere uma tabela (formato markdown ou CSV) com 5 linhas de dados (cenários), contendo as seguintes colunas:

ID_Leitura: (ex: L01, L02...)

Temp_Interna: (Faixa segura: {MIN_TEMP_INTERNA}°C a {MAX_TEMP_INTERNA}°C)

Temp_Externa: (Faixa segura: {MIN_TEMP_EXTERNA} a {MAX_TEMP_EXTERNA}°C)

Integridade_Estrutural: ({OK_INTEGRIDADE_ESTRUTURAL} para Íntegro, {FALHA_INTEGRIDADE_ESTRUTURAL} para Falha)

Nivel_Energia: (0% a 100% - Seguro acima de {MIN_NIVEL_ENERGIA}%)

Pressao_Tanques: (Faixa segura: {MIN_PRESSAO_TANQUES} a {MAX_PRESSAO_TANQUES} bar)

Status_Modulos: ({OK_MODULOS_CRITICOS} para Operacional ou {FALHA_MODULOS_CRITICOS} para Falha)

Requisitos dos cenários:

As 50 primeiras linhas deve ser um cenário de 'Sucesso Total' (todos os dados nominais).

As outras 150 linhas devem conter anomalias variadas (ex: pressão alta, bateria baixa, falha estrutural, temperatura externa crítica) para eu testar a lógica de aborto do meu algoritmo.

Apresente os dados de forma clara e organizada para que eu possa copiar para o meu relatório em PDF
'''
print(prompt)

Atue como um Engenheiro de Sistemas Aeroespaciais da Missão Aurora Siger. Preciso de uma tabela de telemetria de pré-decolagem para alimentar um script Python de validação.

Gere uma tabela (formato markdown ou CSV) com 5 linhas de dados (cenários), contendo as seguintes colunas:

ID_Leitura: (ex: L01, L02...)

Temp_Interna: (Faixa segura: 18°C a 27°C)

Temp_Externa: (Faixa segura: -20 a 40°C)

Integridade_Estrutural: (1 para Íntegro, 0 para Falha)

Nivel_Energia: (0% a 100% - Seguro acima de 80%)

Pressao_Tanques: (Faixa segura: 50 a 120 bar)

Status_Modulos: (1 para Operacional ou 0 para Falha)

Requisitos dos cenários:

As 50 primeiras linhas deve ser um cenário de 'Sucesso Total' (todos os dados nominais).

As outras 150 linhas devem conter anomalias variadas (ex: pressão alta, bateria baixa, falha estrutural, temperatura externa crítica) para eu testar a lógica de aborto do meu algoritmo.

Apresente os dados de forma clara e organizada para que eu possa copiar para o meu relatório em PDF

In [ ]:
%%writefile dados.csv
timestamp,temperatura_interna,temperatura_externa,integridade_estrutural,nivel_energia,pressao_tanques,modulos_criticos
ID_Leitura,Temp_Interna,Temp_Externa,Integridade_Estrutural,Nivel_Energia,Pressao_Tanques,Status_Modulos
L001,22,15,1,95,85,1
L002,23,12,1,96,88,1
L003,21,18,1,94,82,1
L004,24,10,1,98,90,1
L005,25,5,1,92,80,1
L006,22,20,1,97,85,1
L007,20,25,1,99,75,1
L008,23,-5,1,95,95,1
L009,26,-10,1,91,100,1
L010,27,0,1,89,110,1
L011,18,30,1,93,60,1
L012,19,35,1,94,65,1
L013,22,40,1,96,85,1
L014,24,-15,1,98,90,1
L015,25,-20,1,92,115,1
L016,21,15,1,95,80,1
L017,23,12,1,97,88,1
L018,22,18,1,99,82,1
L019,20,10,1,94,90,1
L020,24,5,1,96,85,1
L021,25,20,1,91,78,1
L022,26,25,1,90,75,1
L023,19,-5,1,93,95,1
L024,18,-10,1,95,100,1
L025,22,0,1,98,105,1
L026,23,30,1,92,60,1
L027,24,35,1,97,65,1
L028,21,40,1,94,70,1
L029,20,-15,1,96,110,1
L030,25,-20,1,99,115,1
L031,22,15,1,95,85,1
L032,23,12,1,91,88,1
L033,24,18,1,93,82,1
L034,21,10,1,98,90,1
L035,20,5,1,92,80,1
L036,25,20,1,97,85,1
L037,26,25,1,99,75,1
L038,27,-5,1,88,95,1
L039,18,-10,1,95,100,1
L040,19,0,1,94,110,1
L041,22,30,1,96,60,1
L042,23,35,1,98,65,1
L043,24,40,1,92,85,1
L044,21,-15,1,95,90,1
L045,20,-20,1,97,115,1
L046,25,15,1,99,80,1
L047,26,12,1,91,88,1
L048,22,18,1,93,82,1
L049,23,10,1,98,90,1
L050,24,5,1,96,85,1
L051,30,15,1,95,85,1
L052,32,12,1,96,88,1
L053,35,18,1,94,82,1
L054,15,10,1,98,90,1
L055,10,5,1,92,80,1
L056,22,45,1,97,85,1
L057,20,50,1,99,75,1
L058,23,60,1,95,95,1
L059,26,-25,1,91,100,1
L060,27,-30,1,89,110,1
L061,18,30,0,93,60,1
L062,19,35,0,94,65,1
L063,22,40,0,96,85,1
L064,24,-15,0,98,90,1
L065,25,-20,0,92,115,1
L066,21,15,1,75,80,1
L067,23,12,1,60,88,1
L068,22,18,1,45,82,1
L069,20,10,1,30,90,1
L070,24,5,1,15,85,1
L071,25,20,1,91,130,1
L072,26,25,1,90,145,1
L073,19,-5,1,93,160,1
L074,18,-10,1,95,45,1
L075,22,0,1,98,30,1
L076,23,30,1,92,60,0
L077,24,35,1,97,65,0
L078,21,40,1,94,70,0
L079,20,-15,1,96,110,0
L080,25,-20,1,99,115,0
L081,35,45,1,95,85,1
L082,10,-30,1,96,88,1
L083,28,42,1,94,82,1
L084,16,-22,1,98,90,1
L085,31,50,1,92,80,1
L086,22,15,0,70,85,1
L087,20,25,0,55,75,1
L088,23,-5,0,40,95,1
L089,26,-10,0,25,100,1
L090,27,0,0,10,110,1
L091,18,30,1,93,135,0
L092,19,35,1,94,150,0
L093,22,40,1,96,165,0
L094,24,-15,1,98,40,0
L095,25,-20,1,92,20,0
L096,30,50,0,95,85,1
L097,12,-25,0,96,88,1
L098,33,48,0,94,82,1
L099,14,-28,0,98,90,1
L100,34,55,0,92,80,1
L101,22,15,1,65,140,1
L102,23,12,1,50,155,1
L103,24,18,1,35,170,1
L104,21,10,1,20,35,1
L105,20,5,1,5,15,1
L106,35,20,1,97,85,0
L107,10,25,1,99,75,0
L108,32,-5,1,88,95,0
L109,15,-10,1,95,100,0
L110,30,0,1,94,110,0
L111,22,45,0,60,85,1
L112,23,55,0,45,88,1
L113,24,65,0,30,82,1
L114,21,-35,0,15,90,1
L115,20,-45,0,5,80,1
L116,25,15,1,75,130,0
L117,26,12,1,60,145,0
L118,22,18,1,45,160,0
L119,23,10,1,30,45,0
L120,24,5,1,15,30,0
L121,35,50,1,95,140,1
L122,10,-30,1,96,155,1
L123,32,45,1,94,170,1
L124,15,-25,1,98,35,1
L125,30,55,1,92,15,1
L126,22,15,0,97,85,0
L127,20,25,0,99,75,0
L128,23,-5,0,88,95,0
L129,26,-10,0,95,100,0
L130,27,0,0,94,110,0
L131,35,45,0,93,60,1
L132,10,-25,0,94,65,1
L133,32,50,0,96,85,1
L134,15,-30,0,98,90,1
L135,30,55,0,92,115,1
L136,21,15,1,75,135,1
L137,23,12,1,60,150,1
L138,22,18,1,45,165,1
L139,20,10,1,30,40,1
L140,24,5,1,15,20,1
L141,35,20,1,65,80,1
L142,10,25,1,50,88,1
L143,32,-5,1,35,82,1
L144,15,-10,1,20,90,1
L145,30,0,1,5,85,1
L146,22,45,1,93,140,1
L147,23,55,1,94,155,1
L148,24,65,1,96,170,1
L149,21,-35,1,98,35,1
L150,20,-45,1,92,15,1
L151,35,45,1,75,85,1
L152,10,-30,1,60,88,1
L153,32,50,1,45,82,1
L154,15,-25,1,30,90,1
L155,30,55,1,15,80,1
L156,22,15,0,95,130,1
L157,20,25,0,96,145,1
L158,23,-5,0,94,160,1
L159,26,-10,0,98,45,1
L160,27,0,0,92,30,1
L161,35,20,0,93,60,1
L162,10,25,0,94,65,1
L163,32,-5,0,96,85,1
L164,15,-10,0,98,90,1
L165,30,0,0,92,115,1
L166,21,45,1,75,80,1
L167,23,55,1,60,88,1
L168,22,65,1,45,82,1
L169,20,-35,1,30,90,1
L170,24,-45,1,15,85,1
L171,35,15,1,91,135,1
L172,10,12,1,90,150,1
L173,32,18,1,93,165,1
L174,15,10,1,95,40,1
L175,30,5,1,98,20,1
L176,22,45,0,92,60,1
L177,20,55,0,97,65,1
L178,23,65,0,94,70,1
L179,26,-35,0,96,110,1
L180,27,-45,0,99,115,1
L181,35,45,0,75,140,1
L182,10,-30,0,60,155,1
L183,32,50,0,45,170,1
L184,15,-25,0,30,35,1
L185,30,55,0,15,15,1
L186,22,15,0,65,130,0
L187,20,25,0,50,145,0
L188,23,-5,0,35,160,0
L189,26,-10,0,20,45,0
L190,27,0,0,5,30,0
L191,35,45,1,75,140,0
L192,10,-30,1,60,155,0
L193,32,50,1,45,170,0
L194,15,-25,1,30,35,0
L195,30,55,1,15,15,0
L196,40,60,0,10,180,0
L197,-5,-40,0,5,10,0
L198,45,65,0,8,190,0
L199,-10,-50,0,2,5,0
L200,50,70,0,0,200,0

Overwriting dados.csv

###II. Ler a planilha com o conjunto de dados preparado

In [ ]:
import pandas as pd
import numpy as np

df=pd.read_csv('dados.csv')


# 3. Executar as Verificações (Lógica Condicional)

##a) Verificar se os dados digitados estão dentro das "faixas seguras predefinidas"

In [ ]:
if not(temperatura_interna >= MIN_TEMP_INTERNA and temperatura_interna <= MAX_TEMP_INTERNA):
  resultado_final="DECOLAGEM ABORTADA: Temperatura interna fora da faixa segura"
elif not(temperatura_externa >= MIN_TEMP_EXTERNA and temperatura_externa <= MAX_TEMP_EXTERNA):
  resultado_final="DECOLAGEM ABORTADA: Temperatura externa fora da faixa segura"
elif not(integridade_estrutural == OK_INTEGRIDADE_ESTRUTURAL):
  resultado_final="DECOLAGEM ABORTADA: Integridade estrutural fora da faixa segura"
elif not(nivel_energia >= MIN_NIVEL_ENERGIA):
  resultado_final="DECOLAGEM ABORTADA: Nível de energia fora da faixa segura"
elif not(pressao_tanques >= MIN_PRESSAO_TANQUES and pressao_tanques <= MAX_PRESSAO_TANQUES):
  resultado_final="DECOLAGEM ABORTADA: Pressão dos tanques fora da faixa segura"
elif not(modulos_criticos == OK_MODULOS_CRITICOS):
  resultado_final="DECOLAGEM ABORTADA: Status dos módulos críticos fora da faixa segura"
else:
  resultado_final="PRONTO PARA DECOLAR: Boa viagem!"

##b) Verificar se os dados da planilha estão dentro das "faixas seguras predefinidas"

In [ ]:
for linha in range(1,len(df.values)):
  valor = df.values [linha]
  temperatura_interna = float(valor[1])
  temperatura_externa = float(valor[2])
  integridade_estrutural = int(valor[3])
  nivel_energia = float(valor[4])
  pressao_tanques = float(valor[5])
  modulos_criticos = int(valor[6])
  if not(temperatura_interna >= MIN_TEMP_INTERNA and temperatura_interna <= MAX_TEMP_INTERNA):
    df.loc[linha, 'resultado_final'] = "DECOLAGEM ABORTADA"
    df.loc[linha, 'motivo'] = "Temperatura interna fora da faixa segura"
  elif not(temperatura_externa >= MIN_TEMP_EXTERNA and temperatura_externa <= MAX_TEMP_EXTERNA):
    df.loc[linha, 'resultado_final'] = "DECOLAGEM ABORTADA"
    df.loc[linha, 'motivo'] = "Temperatura externa fora da faixa segura"
  elif not(integridade_estrutural == OK_INTEGRIDADE_ESTRUTURAL):
    df.loc[linha, 'resultado_final'] = "DECOLAGEM ABORTADA"
    df.loc[linha, 'motivo'] = "Integridade estrutural fora da faixa segura"
  elif not(nivel_energia >= MIN_NIVEL_ENERGIA):
    df.loc[linha, 'resultado_final'] = "DECOLAGEM ABORTADA"
    df.loc[linha, 'motivo'] = "Nível de energia fora da faixa segura"
  elif not(pressao_tanques >= MIN_PRESSAO_TANQUES and pressao_tanques <= MAX_PRESSAO_TANQUES):
    df.loc[linha, 'resultado_final'] = "DECOLAGEM ABORTADA"
    df.loc[linha, 'motivo'] = "Pressão dos tanques fora da faixa segura"
  elif not(modulos_criticos == OK_MODULOS_CRITICOS):
    df.loc[linha, 'resultado_final'] = "DECOLAGEM ABORTADA"
    df.loc[linha, 'motivo'] = "Status dos módulos críticos fora da faixa segura"
  else:
    df.loc[linha, 'resultado_final'] = "PRONTO PARA DECOLAR"

# 4. Imprimir o Resultado Final
O sistema não pode deixar dúvidas. O final do código deve compilar todas as verificações e imprimir na tela uma de duas mensagens categóricas:

"PRONTO PARA DECOLAR" (se absolutamente todas as condições forem atendidas).

"DECOLAGEM ABORTADA" (se qualquer uma das condições falhar).

###a) Exibir o resultado final a partir dos dados digitados

In [ ]:
print(resultado_final)

PRONTO PARA DECOLAR: Boa viagem!

###b) Exibir o resultado final a partir da planilha

In [ ]:
df[['resultado_final', 'motivo']]

         resultado_final                                    motivo
0                    NaN                                       NaN
1    PRONTO PARA DECOLAR                                       NaN
2    PRONTO PARA DECOLAR                                       NaN
3    PRONTO PARA DECOLAR                                       NaN
4    PRONTO PARA DECOLAR                                       NaN
..                   ...                                       ...
196   DECOLAGEM ABORTADA  Temperatura interna fora da faixa segura
197   DECOLAGEM ABORTADA  Temperatura interna fora da faixa segura
198   DECOLAGEM ABORTADA  Temperatura interna fora da faixa segura
199   DECOLAGEM ABORTADA  Temperatura interna fora da faixa segura
200   DECOLAGEM ABORTADA  Temperatura interna fora da faixa segura

[201 rows x 2 columns]

In [ ]:
df

,timestamp,temperatura_interna,temperatura_externa,integridade_estrutural,nivel_energia,pressao_tanques,modulos_criticos,resultado_final,motivo
0,ID_Leitura,Temp_Interna,Temp_Externa,Integridade_Estrutural,Nivel_Energia,Pressao_Tanques,Status_Modulos,NaN,NaN
1,L001,22,15,1,95,85,1,PRONTO PARA DECOLAR,NaN
2,L002,23,12,1,96,88,1,PRONTO PARA DECOLAR,NaN
3,L003,21,18,1,94,82,1,PRONTO PARA DECOLAR,NaN
4,L004,24,10,1,98,90,1,PRONTO PARA DECOLAR,NaN
...,...,...,...,...,...,...,...,...,...
196,L196,40,60,0,10,180,0,DECOLAGEM ABORTADA,Temperatura interna fora da faixa segura
197,L197,-5,-40,0,5,10,0,DECOLAGEM ABORTADA,Temperatura interna fora da faixa segura
198,L198,45,65,0,8,190,0,DECOLAGEM ABORTADA,Temperatura interna fora da faixa segura
199,L199,-10,-50,0,2,5,0,DECOLAGEM ABORTADA,Temperatura interna fora da faixa segura
200,L200,50,70,0,0,200,0,DECOLAGEM ABORTADA,Temperatura interna fora da faixa segura